name: Build Docker Image

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
  push:
    branches:
      - main
    paths-ignore:
      - 'docker-compose.yml'
      - 'dev.env'
      - 'blog'
      - 'dev.Dockerfile'
      - 'README.md'
    tags:
      - '*'

jobs:
  create-container:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: test
        run: echo running on branch ${GITHUB_REF}
      -
        name: SANDBOX Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            itohio/web:latest
          platforms: linux/amd64
