
name: Run Tests

on:
  push:
    paths-ignore:
      - 'docker-compose.yml'
      - 'dev.env'
      - 'dev.Dockerfile'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docker-compose.yml'
      - 'dev.env'
      - 'dev.Dockerfile'
      - 'README.md'

jobs:
  build:
    strategy:
      matrix:
        go-version: 
          - 1.19.x
        os: 
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Checkout code
      uses: actions/checkout@v2

    # These are needed for Fyne
    - name: Setup dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

    - name: Test
      run: go test ./...